---
title: "da-ws-04-1"
author: "santowsa, CoWeber, aschupp"
date: "14 November 2017"
output: html_document
---
## Problems which should be corrected during cleaning process

- Header (different row length at the beginning and the end of the table)
- cut rows at the end
- Factor --> Numeric
- N.A. 
- Splitting third column (X.2) to "Orte", " Bezirksinfo" etc. in three columns - Name column names 


## Cleaning the data set according to different problems

```{r, echo=TRUE}
df <- read.table("F:/Data_analysis/data/feldfruechte.txt", header = T,
                 sep = ";", dec = ",", skip = 6, nrows = 8925, 
                 fill = T)

for (c in colnames(df)[4:13]){
  df[, c][df[, c] == "." |
          df[,c]=="," |
          df[,c]=="-" |
          df[,c]=="_" |
          df[,c]=="/" ]<- NA
  df[, c] <- as.numeric(sub(",",".", as.character(df[, c])))
}

names(df) <- c("Year", "ID","Place", "winter wheat", "rye and winter mixed corn",
               "winter barley", "summer barley", "oats", "triticale", "potato",
               "beet", "winter rape", "silage maize")


place <- strsplit(as.character(df$Place),",")

place_dif <- lapply(place, function(i){
  p1 <- sub("^\\s+","",i[1])
  if (length(i)>2){
    p2 <- sub("^\\s+", "", i[2])
    p3 <- sub("^\\s+", "", i[3])
  } else if (length(i) > 1){
    p2 <- sub("^\\s+", "", i[2])
    p3 <- NA
  } else {
    p2 <- NA
    p3 <- NA
  }
  data.frame(A = p1,
             B = p2,
             C = p3)
})

place_dif <- do.call("rbind", place_dif)

place_dif$ID <- df$ID 

place_dif$Year <- df$Year

place_dif[!is.na(place_dif$C),] <- place_dif[!is.na(place_dif$C), c(1,3,2, 4, 5)]

for(r in seq(nrow(place_dif))){
  if(is.na(place_dif$B[r]) &
     grepl("kreis", tolower(place_dif$A[r]))){
    place_dif$B[r] <- "Landkreis"
  }
}

place_dif$B[is.na(place_dif$B) & nchar(as.character(place_dif$ID) == 2)] <- "Bundesland"
place_dif$B[place_dif$ID == "DG"] <- "Land"

df_final <- merge(df, place_dif, by = c("ID", "Year"))

df_final$Place <- NULL

names(df_final) <- c("Year", "ID", "winter wheat", "rye and winter mixed corn",
               "winter barley", "summer barley", "oats", "triticale", "potato",
               "beet", "winter rape", "silage maize", "location", "unit", "additive")

head(df_final)