---
title: "da-ws-06-2"
author: "CoWeber, aschupp, santowsa"
date: "7 Dezember 2017"
output: html_document
---
#### Wheat vs. barley revisited

### read RDS without NA-values
```{r, echo=FALSE}
setwd("D:/mpg/daten/tab")
tabs <- readRDS("feldfruechte_clean.rds")
t1<- tabs[,c(6,8)]
tab <- t1[rowSums(is.na(t1))==0, ]
colnames(tab) <- c("x","y")
```

### leave-many-out cross-validation

```{r, echo=FALSE}
range <- nrow(tab)
nbr <- nrow(tab) * 0.8

cv_sample <- lapply(seq(100), function(i){
  set.seed(i)
  smpl <- sample(range, nbr)
  train <- tab[smpl,]
  test <- tab[-smpl,]
  lmod <- lm(y ~ x, data = train)
  pred <- predict(lmod, newdata = test)
  obsv <- test$y
  resid <- obsv-pred
  ss_obsrv <- sum((obsv - mean(obsv))**2)
  ss_model <- sum((pred - mean(obsv))**2)
  ss_resid <- sum((obsv - pred)**2)
  mss_obsrv <- ss_obsrv / (length(obsv) - 1)
  mss_model <- ss_model / 1
  mss_resid <- ss_resid / (length(obsv) - 2)
  data.frame(pred = pred,
             obsv = obsv,
             resid = resid,
             ss_obsrv = ss_obsrv,
             ss_model = ss_model,
             ss_resid = ss_resid,
             mss_obsrv = mss_obsrv,
             mss_model = mss_model,
             mss_resid = mss_resid,
             r_squared = ss_model / ss_obsrv
  )
})

cv_sample <- do.call("rbind", cv_sample)

ss_obsrv <- sum((cv_sample$obsv - mean(cv_sample$obsv))**2)
ss_model <- sum((cv_sample$pred - mean(cv_sample$obsv))**2)
ss_resid <- sum((cv_sample$obsv - cv_sample$pred)**2)

mss_obsrv <- ss_obsrv / (length(cv_sample$obsv) - 1)
mss_model <- ss_model / 1
mss_resid <- ss_resid / (length(cv_sample$obsv) - 2)
```

### overview of errors used to descirbe the prediction performance:
```{r}
data.frame(NAME = c("cross-validation F value",
                    "linear model F value", 
                    "cross-validatino r squared",
                    "linear model r squared"),
           VALUE = c(round(mss_model / mss_resid, 2),
                     round(anova(lmod)$'F value'[1], 2),
                     round(1 - ss_resid / ss_obsrv, 2),
                     round(summary(lmod)$r.squared, 2)))
```

### variety of different errors
```{r}
se <- function(x) sd(x, na.rm = TRUE)/sqrt(length(na.exclude(x)))

me <- round(mean(cv_sample$pred - cv_sample$obs, na.rm = TRUE), 2)
me_sd <- round(se(cv_sample$pred - cv_sample$obs), 2)
mae <- round(mean(abs(cv_sample$pred - cv_sample$obs), na.rm = TRUE), 2)
mae_sd <- round(se(abs(cv_sample$pred - cv_sample$obs)), 2)
rmse <- round(sqrt(mean((cv_sample$pred - cv_sample$obs)^2, na.rm = TRUE)), 2)
rmse_sd <- round(se((cv_sample$pred - cv_sample$obs)^2), 2)

data.frame(NAME = c("Mean error (ME)", "Std. error of ME", 
                    "Mean absolute error (MAE)", "Std. error of MAE", 
                    "Root mean square error (RMSE)", "Std. error of RMSE"),
           VALUE = c(me, me_sd,
                     mae, mae_sd,
                     rmse, rmse_sd))
```

### print: mean of the root mean square error as well as its minimum, 25% 50% and 75% quantile and maximum value across the cross-validation runs

```{r}
df <- summary(cv_sample$r_squared)
print(df)
```
